language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  include:
    - rust: nightly
      env: FEATURES=nightly

script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES"
