language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      env: FEATURES=nightly

script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES"
